name: 'Behat'

# Controls when the workflow will run
on:
  # Triggers the workflow on all pull request events
  pull_request: { }

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Running tests"
  tests:
    name: 'Stability 1'
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-22.04
    steps:
      # Set PHP version to 8.0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none # disable xdebug, pcov
          tools: cs2pr

      # Checkout Drupal Social.
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Install the version of Open Social under test.
      - name: Composer Install
        run: composer install

      # Install the docker.
      - name: Install Docker
        run: sh scripts/social/ci/install-docker.sh

      - name: Run Docker containers
        run: docker-compose -f docker-compose-ci.yml up -d

      - name: Install Open Social
        run: docker exec -i social_ci_web bash /var/www/scripts/social/install/install_script.sh

      - name: Run Integration tests
        run: docker exec -i social_ci_web bash /var/www/scripts/social/behatstability.sh "stability-1 --stop-on-failure --strict --colors"
